### ISSUE TITLE
Code comment: this style of construct will get you in trouble when you go MP

### ISSUE THREAD

**Issue by robertlipe** [oglavu/RiscV-kernel#1]
First: congrats. Looks like a cool project.

This isn't a bugreport as much as a code comment. Feel free to close it as you wish.

You recently asked about adding MP support. This basic construct shows up in several places, but I'll call out this one as it's easy to reason about.

https://github.com/oglavu/RiscV-kernel/blob/26be42a70312c293411e45dc995a8a0ca2fabcda/src/Scheduler.cpp#L19

Accessing "test and set" variable specifically and globals generally will get you into trouble when you have multiple cores. You're kind of using scheduler:initialized to create a singleton and those are generally bad news on MP or multi-threaded environments. Imagine two different cores that are effectively slightly different speed; perhaps one got distracted by an interrupt or something. Both have executed the "am I initialized?" test, and both got a "nope." One is already off to the races and initializes the scheduler and schedules something. The second has a slight pause between the test and the call to initialize the scheduler. The scheduler now gets initialized again, which probably loses whatever the first core just scheduled because you've initialized the scheduler twice.

The poor solution would be to guard that with some kind of a lock primitive.
The better solution is to just initialize the scheduler when you create that object. It's not unreasonable to have main() - or something - just create and initialize this object fully.

There are a few occurrences of this basic issue that'll have to be rethought when moving to multi-core. This was just the easiest to talk through. Partially constructed objects that are demand-filled like this are worth avoiding when you can.

Global data in general will have to be broken into two parts: one that's actually per-core (e.g.: kernel stack) and those rare remaining data objects that really ARE globals, but that'll have to be protected by a locking primitive. These are worth minimizing. if you can design around them.

When using uncommon acronyms like PCB, spell it out at least once. I'm a former OS developer and don't really know what it means in tis project. Process Control Block?

https://github.com/oglavu/RiscV-kernel/blob/26be42a70312c293411e45dc995a8a0ca2fabcda/src/pcb.cpp#L134C19-L134C25

Is just unnecessarily awkward. Isn't that "status != nullptr"?

https://github.com/oglavu/RiscV-kernel/blob/26be42a70312c293411e45dc995a8a0ca2fabcda/h/sem.hpp#L15

Your naming convention would benefit from marking class-local data in some way. Google's style guide would call for 'n' to be named something more strongly, but would make it be named "n_".  A reader of the code knows that anything that's foo_ is class-local. I think Microsoft's style guide calls for it that be "m_n" or such. It helps distinguish between locals and member variables.

Also, on this member specifically, rather than casting it in so many places, just accept that sign bit and call it a signed int instead of an unsigned and casting it to signed.

https://github.com/oglavu/RiscV-kernel/blob/26be42a70312c293411e45dc995a8a0ca2fabcda/src/sem.cpp#L65

Could either return an std::optional (should work in freestanding...) or just return two types: one that's the return value and one that's the semaphore. In RISC-V, the first four (?) will be returned in registers so it works really well. You have several occurrences of in-out args liek this.

I'm thinking about https://github.com/oglavu/RiscV-kernel/blob/26be42a70312c293411e45dc995a8a0ca2fabcda/h/RiscV.hpp#L128C29-L129C1 and friends and how they're used to build ecalls. I think that the way you're calling them, the register allocator doesn't know that a[0-7] are dirty and the optimizer COULD potentially use them between the time you load them and the time you make the ecall. Best practices that I've seen that lets the register allocator know that a0-a7 are used tend to look something like:
https://github.com/riscvarchive/riscv-linux/blob/32b1573d1f118844d859341d095e005ca5ba572e/arch/riscv/include/asm/sbi.h#L30 (Note this is an SBI call and not a conventional ecall, but the boilerplate applies.) Generally any time you hardcode a register inside an asm but dont' make it visible in the = or + constraints fields of the asm, it's a flag that you can get code that works MOST of the time, but can be subtly broken at different optimization levels, new versions, something different gets inlined and uses different registers, etc. Always let the GCC's register allocator in on what registers you're using behind its back. syscall_c looks pretty fragile in this regard.

Overall, this is a very cool project. You've made disciplined use of C++ in a kernel and it's all quite readable. You're of course free to ignore any or all of the above; they're just comments and concerns I had while skimming the code.

Good luck!

**Comment by oglavu** [comment]
Foremost: I truely appreciate your comment. It is very constructive.

Regarding the first issue pointed out: yes,

**Comment by oglavu** [comment]
Foremost: I truely appreciate your comment. It is highly constructive.

Issue of potentially compromised initialisation of global variables is definately just a part of a greater problem of shifting from single-core to multi-core architecture.  Many design decisions I made are not applicable when it comes to MP. On the other hand, I had and I have many courses dedicated to synchronization-related problems. I will bear your suggestion in mind.

Yes, PCB stands for Process Control Block. I omitted the definitions of some abbriviations commonly used at the faculty because I thought this project wouldn't go out the scope of it.

Status [here](https://github.com/oglavu/RiscV-kernel/blob/26be42a70312c293411e45dc995a8a0ca2fabcda/src/pcb.cpp#L134C19-L134C25) points to the boolean in [main.cpp](https://github.com/oglavu/RiscV-kernel/blob/ac867416a5161e64b43774d671eb3ee69e52c64b/src/main.cpp#L31) that signals the output thread whether it should be active or not. After the execution of userMain, the kernelThreadStatus is set to false meaning all system threads (outputThread) should finish.

I should definately reconsider the naming convention, particularly with regards to sem::n. And once and for all change its type to int. 

In-out args are the legacy of the project specification at the faculty, but since it's gone for good (I passed), I might change it.

> I'm thinking about https://github.com/oglavu/RiscV-kernel/blob/26be42a70312c293411e45dc995a8a0ca2fabcda/h/RiscV.hpp#L128C29-L129C1 and friends and how they're used to build ecalls. I think that the way you're calling them, the register allocator doesn't know that a[0-7] are dirty and the optimizer COULD potentially use them between the time you load them and the time you make the ecall. Best practices that I've seen that lets the register allocator know that a0-a7 are used tend to look something like:
https://github.com/riscvarchive/riscv-linux/blob/32b1573d1f118844d859341d095e005ca5ba572e/arch/riscv/include/asm/sbi.h#L30 (Note this is an SBI call and not a conventional ecall, but the boilerplate applies.) Generally any time you hardcode a register inside an asm but dont' make it visible in the = or + constraints fields of the asm, it's a flag that you can get code that works MOST of the time, but can be subtly broken at different optimization levels, new versions, something different gets inlined and uses different registers, etc. Always let the GCC's register allocator in on what registers you're using behind its back. syscall_c looks pretty fragile in this regard.

This is an execellent piece of advice. I will most definately adopt it.

At the end, I want to thank you once again for pointing these out. Advice provided is thoroughly invaluable and I am most gratious for time set aside to look up my project.

Best regards!
